# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

alias ls='ls -F --color=auto --show-control-chars'
alias ll='ls -l'
alias l='ls -CF'
alias la='ls -A'

